

PNGFILES_FROM_XPM = 


PNGFILES_STATIC = \
           MainScreenGreekExample.png MainScreen.png ToolBar.png MenuBar.png \
           MyPgConnSettingsFilled.png MyPgSQLConnSettings.png \
           SQLiteConnSettingsFilled.png SQLiteConnSettings.png \
           commit.png \
           connect.png \
           flash.png \
           leftarrow.png \
           rightarrow.png \
           together.png 
	   


PNGFILES_ALL = $(PNGFILES_FROM_XPM) \
               $(PNGFILES_STATIC)

PNGFILES_DISTCLEAN = $(PNGFILES_FROM_XPM) 


